development: &defaults
  adapter: sqlite3
  database: db/photos.db
  timeout: 25000
  
production: # fotos.noort.be
  <<: *defaults
  #encoding: unicode
  #adapter: postgresql
  #username: mzrdmhlqax
  #port: 5432
  #host: @ec2-184-72-255-44.compute-1.amazonaws.com
  #database: mzrdmhlqax
  #password: f5lxx1zz5pnorynqglhzmsp34